version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/" 
    target-branch: "main"
    schedule:
      interval: "weekly" 
    labels:
      - "dependabot-PR" 
    metadata:
      runner: "self-hosted"
      group: "dependabot-runner"  

