# Sample GitHub Organization code security configuration YAML
# Fill in or modify values as needed

target_type: "organization"
name: "sample"
description: "This is a code security configuration for my-org repositories"
advanced_security: "enabled"
dependency_graph: "enabled"
dependency_graph_autosubmit_action: "not_set"
dependency_graph_autosubmit_action_options:
  labeled_runners: false
dependabot_alerts: "enabled"
dependabot_security_updates: "not_set"
code_scanning_default_setup: "enabled"
code_scanning_default_setup_options:
  runner_type: "not_set"
  runner_label: null
secret_scanning: "enabled"
secret_scanning_push_protection: "enabled"
secret_scanning_validity_checks: "enabled"
secret_scanning_non_provider_patterns: "enabled"
private_vulnerability_reporting: "disabled"
enforcement: "enforced"