# TLC recommended GitHub Organization code security configuration YAML
# GHES 3.16

# target_type: "organization"
name: "TLC_recommended"
description: "This is a code security configuration for repositories"

# DEPENDENCY SCANNING
advanced_security: "enabled"
dependency_graph: "enabled"
dependency_graph_autosubmit_action: "not_set"
dependency_graph_autosubmit_action_options:
  labeled_runners: false
dependabot_alerts: "enabled"
dependabot_security_updates: "disabled" #GHES
private_vulnerability_reporting: "enabled"

# SECRET SCANNING
secret_scanning: "enabled"
secret_scanning_validity_checks: "disabled" # send to partners
secret_scanning_non_provider_patterns: "enabled"
#secret_scanning_generic_secrets: "not_set" #AI 
secret_scanning_push_protection: "enabled"
secret_scanning_delegated_bypass: "enabled"
secret_scanning_delegated_bypass_options:
  reviewers:
  - reviewer_type: "ROLE"
    reviewer_id: 5 # 5 is the GitHub internal ID for the Repository admin role
#secret_scanning_delegated_alert_dismissal: "not_set" #AI 

# CODE SCANNING
code_scanning_default_setup: "enabled"
code_scanning_default_setup_options:
  runner_type: "not_set"
  runner_label: null # label TBC
# code_scanning_options:  # Not available GHES
#   allow_advanced: true
# code_scanning_delegated_alert_dismissal: "enabled"

# POLICY
default_for_new_repos: all  # all, public, private, internal, none
enforcement: "enforced"
